/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package puzzle;

import java.awt.Graphics;
import java.awt.Image;
import java.io.IOException;
import java.io.InputStream;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JRootPane;
import puzzle.model.LoginModel;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author antoroko
 */

public class Login extends javax.swing.JFrame {
    
    public Login() {
        initComponents();
        setLocationRelativeTo(null); //centers the form   
        
        LoginModel lg = new LoginModel();
        
        try {
            users = lg.getUser();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        int counter=0;
               
        for (int i=0; i<users.length;i++){
            if(users[i][1]!=null) {
                counter++;
            } 
        }
               
        for(int i=0; i <=counter-1 ;i++){
            
            cmbUsers.addItem(users[i][2]+" "+users[i][3]); 
        }
        
        //play welcome voice
        sound("/audio/theme-welcome.wav");
    }
    
    public final void sound(String path)
    {
        InputStream in;
        try{
            in= this.getClass().getResourceAsStream(path);
            stream = new AudioStream(in);
            AudioPlayer.player.start(stream);
            }
            catch(IOException e){
                e.printStackTrace();
            } 
    }
    
    private class LoginPanel extends JPanel {
        private Image pimg;
        
            public LoginPanel() {
                try {
                    ImageIcon icon = new ImageIcon(this.getClass().getResource("/images/login.png"));
                    pimg = icon.getImage();
                  } catch (Exception e) {
                      e.printStackTrace();
                  }
            }       

            @Override
            protected void paintComponent(Graphics g) {
                    super.paintComponent(g);
                                    // paint the background image and scale it to fill the entire space
                    g.drawImage(pimg, 0, 0, getWidth(), getHeight(), this);
            }
        
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
                            
        private void initComponents() {
            
        this.setIconImage(new ImageIcon(getClass().getResource(
				PuzzleProperties.APPLICATION_ICON_FILE)).getImage());
        
        LoginPanel = new LoginPanel();
        btnLogin = new javax.swing.JToggleButton();
        panelLogin = new javax.swing.JPanel();
        cmbUsers = new javax.swing.JComboBox();
        btnLog = new javax.swing.JButton();
        btnNewPupil = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblLogTitle = new javax.swing.JLabel();
                        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(970, 647));
        this.setUndecorated(true);
        this.getRootPane().setWindowDecorationStyle(JRootPane.NONE);

        LoginPanel.setBackground(new java.awt.Color(255, 255, 255));
        LoginPanel.setPreferredSize(new java.awt.Dimension(970, 647));

        btnLogin.setFont(new java.awt.Font("DK Crayon Crumble", 1, 36)); 
        btnLogin.setText("Enter Class");
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/enter.png")));
        btnLogin.setBackground(new java.awt.Color(47, 28, 18));
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        panelLogin.setBackground(new java.awt.Color(213, 210, 208));
        panelLogin.setVisible(false);
        
        cmbUsers.setFont(new java.awt.Font("DK Crayon Crumble", 0, 24)); // NOI18N
        cmbUsers.setModel(new javax.swing.DefaultComboBoxModel(new String[] { }));

        btnLog.setFont(new java.awt.Font("DK Crayon Crumble", 0, 24)); 
        btnLog.setBackground(new java.awt.Color(66, 139, 202));
        btnLog.setText("Enter");
        btnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogActionPerformed(evt);
            }
        });

        lblLogTitle.setFont(new java.awt.Font("DK Crayon Crumble", 1, 24)); // NOI18N
        lblLogTitle.setText("Select your name:");
        lblLogTitle.setForeground(new java.awt.Color(47, 28, 18));
        

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        )
                    .addComponent(lblLogTitle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    
                    .addComponent(btnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnNewPupil.setText("New Pupil");
        btnNewPupil.setFont(new java.awt.Font("DK Crayon Crumble", 0, 24)); 
        btnNewPupil.setBackground(new java.awt.Color(66, 139, 202));
        btnNewPupil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pupil.png")));
        btnNewPupil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewPupilActionPerformed(evt);
            }
        });

        btnExit.setText("Close");
        btnExit.setFont(new java.awt.Font("DK Crayon Crumble", 1, 24)); 
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/close.png")));
        btnExit.setBackground(new java.awt.Color(190, 30, 45));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPanelLayout.createSequentialGroup()
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(0, 220, Short.MAX_VALUE)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNewPupil, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(117, 117, 117))
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewPupil, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
        );

        pack();
    }                        

    private void btnNewPupilActionPerformed(java.awt.event.ActionEvent evt) {                                            
        AudioPlayer.player.stop(stream);
        Register.display();
        this.dispose();
    }                                           

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
         boolean log = btnLogin.isSelected();
            if(log == true) {
                panelLogin.setVisible(true);
            } else {
                panelLogin.setVisible(false);
            }
    }                                        

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {                                        
        this.dispose();
        System.exit(0);
    }                                       

    private void btnLogActionPerformed(java.awt.event.ActionEvent evt) {                                              
        final String args = String.valueOf(cmbUsers.getSelectedItem());
        final String index = String.valueOf(cmbUsers.getSelectedIndex());
                
        AudioPlayer.player.stop(stream);
        
        Main mobj = new Main(args,index,users);
        mobj.start();
        
        try {
            Thread.sleep(2000);
        } catch (InterruptedException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
                
        this.dispose();
    }                                      

    /**
     * @param args the command line arguments
     */
    public static void display() {
            try {
                Thread.sleep(4000);
            } catch (InterruptedException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        /* Set the Nimbus look and feel */
    
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLog;
    private javax.swing.JToggleButton btnLogin;
    private javax.swing.JButton btnNewPupil;
    private javax.swing.JComboBox cmbUsers;
    private javax.swing.JPanel panelLogin;
    private LoginPanel LoginPanel;    
    private javax.swing.JLabel lblLogTitle;
    private String [][] users = new String[100][10];
    AudioStream stream;
    

}
