/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package puzzle;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JRootPane;
import static puzzle.ui.GameMainWindow.newgame;
import speech.ListenToMe;

/**
 *
 * @author antoroko
 */
public class Pronounce extends javax.swing.JDialog {

    public Pronounce() {
        initComponents();
        setLocationRelativeTo(null); //centers the form        
    }
    
    private class PronouncePanel extends JPanel {
        private Image pimg;
        
            public PronouncePanel() {
                try {
                    ImageIcon icon = new ImageIcon(this.getClass().getResource("/images/blackboard2.png"));
                    pimg = icon.getImage();
                  } catch (Exception e) {
                      e.printStackTrace();
                  }
            }       

            @Override
            protected void paintComponent(Graphics g) {
                    super.paintComponent(g);
                                    // paint the background image and scale it to fill the entire space
                    g.drawImage(pimg, 0, 0, getWidth(), getHeight(), this);
            }
        
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pronouncePanel = new PronouncePanel();
        lblDescription = new javax.swing.JLabel();
        lblScore = new javax.swing.JLabel();
        lblLoading = new javax.swing.JLabel();
        tbtnRead = new javax.swing.JToggleButton();
        btnClose = new javax.swing.JButton();
        btnPlayAgain = new javax.swing.JButton();
        
        lblLoading.setVisible(false);
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));
        this.setUndecorated(true);
        this.getRootPane().setWindowDecorationStyle(JRootPane.NONE);

        pronouncePanel.setBackground(new java.awt.Color(255, 255, 255));
        pronouncePanel.setPreferredSize(new java.awt.Dimension(400, 230));

        lblDescription.setFont(new java.awt.Font("DK Crayon Crumble", 0, 48)); 
        lblDescription.setForeground(new java.awt.Color(255, 255, 255));
        lblDescription.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDescription.setText("This is a "+imageName);
        
        lblScore.setFont(new java.awt.Font("MV Boli", 0, 30)); 
        lblScore.setForeground(new java.awt.Color(244, 131, 101));
        lblScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblScore.setText("Scored: "+marks+" \u0025 ("+getComment()+")");

        tbtnRead.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        tbtnRead.setBackground(new java.awt.Color(188, 253, 36));
        tbtnRead.setForeground(new java.awt.Color(7, 59, 46));
        tbtnRead.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/read.png"))); // NOI18N
        tbtnRead.setText("Click to Read");
        tbtnRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnReadActionPerformed(evt);
            }
        });

        btnClose.setBackground(new java.awt.Color(10, 84, 61));
        btnClose.setFont(new java.awt.Font("Tekton Pro", 1, 14)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setText("X");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnPlayAgain.setBackground(new java.awt.Color(255, 194, 30));
        btnPlayAgain.setFont(new java.awt.Font("Tekton Pro", 1, 36)); // NOI18N
        btnPlayAgain.setForeground(new java.awt.Color(153, 51, 0));
        btnPlayAgain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/repeat.png"))); // NOI18N
        btnPlayAgain.setText(" Play Again");
        btnPlayAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayAgainActionPerformed(evt);
            }
        });
		
		lblLoading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/loading.gif"))); // NOI18N

        javax.swing.GroupLayout pronouncePanelLayout = new javax.swing.GroupLayout(pronouncePanel);
        pronouncePanel.setLayout(pronouncePanelLayout);
        pronouncePanelLayout.setHorizontalGroup(
            pronouncePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)            
            .addGroup(pronouncePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(210, 210, 210)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pronouncePanelLayout.createSequentialGroup()
                        .addComponent(lblScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)                            
                        .addGap(10, 10, 10))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pronouncePanelLayout.createSequentialGroup()                                                
                        .addComponent(tbtnRead, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(209, 209, 209)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pronouncePanelLayout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addGroup(pronouncePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pronouncePanelLayout.createSequentialGroup()
                        .addComponent(btnPlayAgain, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(176, 176, 176))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pronouncePanelLayout.createSequentialGroup()
                        .addComponent(btnClose)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pronouncePanelLayout.createSequentialGroup()
                        .addComponent(lblLoading)
                        .addGap(250, 250, 250))))
        );
        pronouncePanelLayout.setVerticalGroup(
            pronouncePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pronouncePanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(lblDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(lblScore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbtnRead)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoading)
                .addGap(34, 34, 34)
                .addComponent(btnPlayAgain)
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pronouncePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pronouncePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void tbtnReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnReadActionPerformed
        boolean tbrd = tbtnRead.isSelected();
        ListenToMe lobj = new ListenToMe(imageName);
        
        if(tbrd == true) {
            tbtnRead.setFont(new java.awt.Font("Tekton Pro", 0, 24)); 
            tbtnRead.setBackground(new java.awt.Color(255, 216, 1));
            tbtnRead.setForeground(new java.awt.Color(255, 0, 18));
            tbtnRead.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/read.png")));                      
            tbtnRead.setText("Listening...");                        
            lobj.start();
            lblLoading.setVisible(true);
            
        } else {
            tbtnRead.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
            tbtnRead.setBackground(new java.awt.Color(188, 253, 36));
            tbtnRead.setForeground(new java.awt.Color(7, 59, 46));
            tbtnRead.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/read.png"))); // NOI18N
            tbtnRead.setText("Click to Read");              
            //lobj.mstop();                       
            lblLoading.setVisible(false);
            
        }
        
        
    }//GEN-LAST:event_tbtnReadActionPerformed

    private void btnPlayAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayAgainActionPerformed        
        newgame();
        PuzzleTimer.resetCounter();
        this.dispose();
    }//GEN-LAST:event_btnPlayAgainActionPerformed

    /**
     * @param args
     * @param mks
     */
    public static void display (String args, int mks) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pronounce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pronounce().setVisible(true);
            }
        });
        imageName = args;
        marks = String.valueOf(mks);
    }
    
    public static String getComment() {
        int mks = Integer.parseInt(marks);
        if(mks >= 90) {
            return "Excellent!";
        } else if (mks >= 80) {
            return "Very Good!";
        } else if (mks >= 70) {
            return "Good!";
        } else if (mks >= 50) {
            return "Fair!";
        } else {
            return "Poor!";
        }  
    }
    
    // Variables declaration
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnPlayAgain;
    private static javax.swing.JLabel lblDescription;
    private static javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblLoading;
    private PronouncePanel pronouncePanel;
    private javax.swing.JToggleButton tbtnRead;    
    private static String imageName;
    private static String marks;
        
}
